auth_magic: 5quOREeqB5UWl7Wnatyhbq8vbXIuDHIw
password_hash_algos: sha256
shop_name: hotpotshop
force_ssl: null
admin_allow_host: {  }
cookie_lifetime: 0
cookie_name: eccube
locale: ja
timezone: Asia/Tokyo
pageinrange: false
trusted_proxies_connection_only: false
trusted_proxies: {  }
eccube_install: 1
